server.port=${SERVER_PORT:8081}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.url=${POSTGRES_URL}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect